### ISSUE TITLE
Add more server domain options since sci-hub.cc is blocked sometime

### ISSUE THREAD

**Issue by mingsu** [bibcure/sci2pdf#10]
As mentioned, is it possible to add one more option to choose server domain?

**Comment by crystoneme** [comment]
+1
do you have the plan to add sic-hub.la？

**Comment by mgiugliano** [comment]
sci-hub.cc no longer works and must be replaced by a new url. 
I failed to locate the place in the script where the URL is encoded.

Where is it, so that I change it myself...?

**Comment by lambdamusic** [comment]
Same error here

```
Traceback (most recent call last):
  File "/usr/local/bin/scihub2pdf", line 191, in <module>
    main()
  File "/usr/local/bin/scihub2pdf", line 148, in main
    download_from_doi(value, location, use_libgen)
  File "/usr/local/lib/python3.7/site-packages/scihub2pdf/download.py", line 163, in download_from_doi
    download_from_scihub(doi, pdf_file)
  File "/usr/local/lib/python3.7/site-packages/scihub2pdf/download.py", line 99, in download_from_scihub
    found, r = ScrapSci.navigate_to(doi, pdf_file)
  File "/usr/local/lib/python3.7/site-packages/scihub2pdf/scihub.py", line 87, in navigate_to
    r = requests.get(self.sci_url)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sci-hub.cc', port=80): Max retries exceeded with url: /10.1016/0306-4379(78)90013-3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10cd68cf8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```
