### ISSUE TITLE
Exceptions with example sci2pdf 10.1038/s41524-017-0032-0

### ISSUE THREAD

**Issue by jvw1954** [bibcure/sci2pdf#2]
Debian 8

jaap@jaap:/$ sci2pdf 10.1038/s41524-017-0032-0
10.1038/s41524-017-0032-0
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sci2pdf", line 80, in <module>
    main()
  File "/usr/local/bin/sci2pdf", line 68, in main
    download_from_doi(value, location)
  File "/usr/local/lib/python3.4/dist-packages/sci2pdf/libgen.py", line 91, in download_from_doi
    bib_libgen = get_libgen_url(bib)
  File "/usr/local/lib/python3.4/dist-packages/sci2pdf/libgen.py", line 22, in get_libgen_url
    r = requests.get(url, params=params, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
jaap@jaap:/$

**Comment by devmessias** [comment]
Please,  you can run the following command?
(if you using pip)
```
pip show sci2pdf
```
(if you using pip3)
```
pip3 show sci2pdf
```
Should return Version: 0.0.3,

**Comment by devmessias** [comment]
@jvw1954 Pealse see #3.

I worked yesterday on a direct integration with scihub (rather than libgen) the only annoying thing about this is the captcha system of sci-hub. Probably the next version will allow users choose which system(libgen or scihub) scihub2pdf should use.

**Comment by devmessias** [comment]
This issue was solved with the new version. Now the system uses sci-hub as default.
In addition, the package name was changed, from sci2pdf to scihub2pdf(beta version)

You need to install the new package,
```
$ sudo pip uninstall sci2pdf
$ sudo pip install scihub2pdf
```
 please, read [README.md](README.md)
